### ISSUE TITLE
Little endian/big endian

### ISSUE THREAD

**Issue by allan-simon** [aviddiviner/go-murmur#1]
Hello

I'm a  noob in hashing function. but i was wondering  that it seems in your implementation you have some operations for changing the little-endian/big endian,  I was wondering if it was only to be compatible with murmur2, or if it was absolutely for the hash function to work as expected (i.e if not necessary, would be it to possible to have a hash function without them,  just that it will not be "murmur2" )

**Comment by aviddiviner** [comment]
>  it seems in your implementation you have some operations for changing the little-endian/big endian

Which operations are you referring to? Point me to the line of code.
Thanks!

**Comment by allan-simon** [comment]
Yup sorry to not have included that ^^

https://github.com/aviddiviner/go-murmur/blob/master/murmur2.go#L38

but actually now that I ready it carefully , it's not what I thought (i thought it was byte reordering, as in C implementation one can directly cast at his own risk the 4 bytes into one uint64 )

**Comment by aviddiviner** [comment]
This might give you some clarity:

``` go
data := []byte("Hello, playground")
fmt.Printf("%b %b %b %b\n", data[3], data[2], data[1], data[0])
// 1101100 1101100 1100101 1001000

k := uint32(data[0]) | uint32(data[1])<<8 | uint32(data[2])<<16 | uint32(data[3])<<24
fmt.Printf("%b\n", k)
// 1101100011011000110010101001000
```

_https://play.golang.org/p/8i6cSEObrP_
Just making a 32-bit int by shifting and OR-ing four 8-bit bytes.
HTH
